name: EdgeVoice Benchmark

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show system information
        run: |
          echo "===== SYSTEM INFORMATION ====="
          uname -a
          echo "===== ARCHITECTURE ====="
          uname -m
          echo "===== PYTHON ====="
          python3 --version

      - name: Run EdgeVoice
        run: |
          printf "What is AI?\nexit\n" | python3 app.py

      - name: Run benchmark
        run: |
          python3 benchmark.py
